export const imagesFranchise = [
  {
    alt: "visa",
    src: "https://secure.epayco.co/img/standard/franquicias/visa.png",
    width: 30,
    height: 20,
    showPay: true,
    bin: [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
  },
  {
    alt: "master",
    src: "https://secure.epayco.co/img/standard/franquicias/master.png",
    width: 30,
    height: 20,
    showPay: true,
    bin: [51, 52, 53, 54, 55],
  },
  {
    alt: "amex",
    src: "https://secure.epayco.co/img/standard/franquicias/american.png",
    width: 30,
    height: 20,
    showPay: true,
    bin: [34, 37],
  },
  {
    alt: "diners",
    src: "https://secure.epayco.co/img/standard/franquicias/diners.png",
    width: 30,
    height: 20,
    showPay: true,
    bin: [36, 38, 39],
  },
  {
    alt: "credent",
    src: "https://secure.epayco.co/img/standard/franquicias/credencial.png",
    width: 30,
    height: 20,
    showPay: false,
  },
  {
    alt: "codensa",
    src: "https://secure.epayco.co/img/standard/franquicias/codensa.png",
    width: 30,
    height: 20,
    showPay: false,
  },
];

export const banks = [
  { id: "1815", value: "ALIANZA FIDUUCIARIA " },
  { id: "1558", value: "BAN100" },
  { id: "1059", value: "BANCAMIA S.A." },
  { id: "1040", value: "BANCO AGRARIO" },
  { id: "1052", value: "BANCO AV VILLAS" },
  { id: "1013", value: "BANCO BBVA COLOMBIA S.A. " },
  { id: "1032", value: "BANCO CAJA SOCIAL " },
  { id: "1066", value: "BANCO COOPERATIVO COOPCENTRAL " },
  { id: "1051", value: "BANCO DAVIVIENDA " },
  { id: "1001", value: "BANCO DE BOGOTA" },
  { id: "1023", value: "BANCO DE OCCIDENTE " },
  { id: "1062", value: "BANCO FALABELLA" },
  { id: "1063", value: "BANCO FINANDINA S.A. BIC " },
  { id: "1012", value: "BANCO GNB SUDAMERIS " },
  { id: "1006", value: "BANCO ITAU" },
  { id: "1071", value: "BANCO J.P. MORGAN COLOMBIA S.A. " },
  { id: "1047", value: "BANCO MUNDO MUJER S.A. " },
  { id: "1060", value: "BANCO PICHINCHA S.A. " },
  { id: "1002", value: "BANCO POPULAR" },
  { id: "1065", value: "BANCO SANTANDER COLOMBIA " },
  { id: "1069", value: "BANCO SERFINANZA " },
  { id: "1303", value: "BANCO UNION antes GIROS " },
  { id: "1007", value: "BANCOLOMBIA" },
  { id: "1061", value: "BANCOOMEVA S.A." },
  { id: "1808", value: "BOLD CF" },
  { id: "1283", value: "CFA COOPERATIVA FINANCIERA " },
  { id: "1009", value: "CITIBANK" },
  { id: "1370", value: "COLTEFINANCIERA" },
  { id: "1292", value: "CONFIAR COOPERATIVA FINANCIERA " },
  { id: "1289", value: "COTRAFA" },
  { id: "1816", value: "CREZCAMOS" },
  { id: "1097", value: "DALE" },
  { id: "1551", value: "DAVIPLATA" },
  { id: "1637", value: "IRIS" },
  { id: "1286", value: "JFK COOPERATIVA FINANCIERA " },
  { id: "1070", value: "LULO BANK" },
  { id: "1801", value: "MOVII S.A." },
  { id: "1507", value: "NEQUI" },
  { id: "1809", value: "NU" },
  { id: "1811", value: "RAPPIPAY" },
  { id: "1019", value: "SCOTIABANK COLPATRIA " },
  { id: "1804", value: "UALÁ" },
];
